const PROBLEMS = [
    {
        id: 'bash',
        name: '巴什博弈',
        description: '一堆n个石子，两人轮流取1~m个，取走最后一个者胜。',
        difficulty: 'easy',
        piles: [20],
        maxTake: 3,
        rule: 'bash',
        timeLimit: 30,
        n: 20, m: 3
    },
    {
        id: 'nim',
        name: 'Nim 游戏',
        description: '三堆石子，两人轮流从任意一堆取任意数量，取走最后一个者胜。',
        difficulty: 'medium',
        piles: [3, 4, 5],
        maxTake: null,
        rule: 'nim',
        timeLimit: 45,
    },
    {
        id: 'nim-lite',
        name: 'Nim 简化版',
        description: '两堆石子，每堆5个。两人轮流从任意一堆取任意数量。',
        difficulty: 'easy',
        piles: [5, 5],
        maxTake: null,
        rule: 'nim',
        timeLimit: 30,
    },
    {
        id: 'wythoff',
        name: '威佐夫博弈',
        description: '两堆石子，可从一堆取任意数量，或从两堆取相同数量。',
        difficulty: 'hard',
        piles: [6, 10],
        maxTake: null,
        rule: 'wythoff',
        timeLimit: 45,
    },
    {
        id: 'bash-big',
        name: '巴什博弈·进阶',
        description: '一堆50个石子，每次取1~5个，取走最后一个者胜。',
        difficulty: 'medium',
        piles: [50],
        maxTake: 5,
        rule: 'bash',
        timeLimit: 45,
        n: 50, m: 5
    },
    {
        id: 'nim-hard',
        name: 'Nim 挑战',
        description: '四堆石子：1,3,5,7。经典的Nim必败局面，看谁能抓住机会！',
        difficulty: 'hard',
        piles: [1, 3, 5, 7],
        maxTake: null,
        rule: 'nim',
        timeLimit: 60,
    }
];