const PROBLEMS = [
    {
        id: 'bash',
        name: '巴什博弈',
        icon: '🪨',
        description: '一堆石子，两人轮流取1~m个，取走最后一个者胜。',
        difficulty: 'easy',
        defaultPiles: [20],
        maxTake: 3,
        rule: 'bash',
        timeLimit: 30,
        boardType: 'single-row',
        ai: { style: 'aggressive' },
        customizable: true,
        configLabel: '石子数量',
        configPlaceholder: '石子数量',
        link: 'https://www.luogu.com.cn/problem/P2197'
    },
    {
        id: 'nim',
        name: 'Nim 游戏',
        icon: '🎯',
        description: '多堆石子，轮流从任意一堆取任意数量，取走最后一个者胜。',
        difficulty: 'medium',
        defaultPiles: [3, 4, 5],
        maxTake: null,
        rule: 'nim',
        timeLimit: 45,
        boardType: 'multi-pile',
        ai: { style: 'destroyer' },
        customizable: true,
        configLabel: '堆数',
        configPlaceholder: '堆数（随机每堆石子）',
        link: 'https://www.luogu.com.cn/problem/P2197'
    },
    {
        id: 'wythoff',
        name: '威佐夫博弈',
        icon: '⚖️',
        description: '两堆石子，可从一堆取任意数量，或从两堆取相同数量。',
        difficulty: 'hard',
        defaultPiles: [6, 10],
        maxTake: null,
        rule: 'wythoff',
        timeLimit: 45,
        boardType: 'wythoff',
        ai: { style: 'balancer' },
        customizable: true,
        configLabel: '两堆数量（逗号分隔）',
        configPlaceholder: '如: 6, 10',
        link: 'https://www.luogu.com.cn/problem/P2252'
    },
    {
        id: 'euclid',
        name: '欧几里德的游戏',
        icon: '📐',
        description: '两个正整数，每次将较大数减去较小数的任意倍（非负），先减到0者胜。',
        difficulty: 'medium',
        defaultPiles: [25, 7],
        maxTake: null,
        rule: 'euclid',
        timeLimit: 60,
        boardType: 'euclid',
        ai: { style: 'balancer' },
        customizable: true,
        configLabel: '两个数（逗号分隔）',
        configPlaceholder: '如: 25, 7',
        link: 'https://www.luogu.com.cn/problem/P1290'
    },
    {
        id: 'decreasing',
        name: '递减游戏',
        icon: '📉',
        description: '多个正整数，每次选一个>1的数减1，无法操作者输。',
        difficulty: 'easy',
        defaultPiles: [3, 4, 5],
        maxTake: null,
        rule: 'decreasing',
        timeLimit: 45,
        boardType: 'multi-pile',
        ai: { style: 'cautious' },
        customizable: true,
        configLabel: '堆数（每个数随机）',
        configPlaceholder: '堆数',
        link: 'https://www.luogu.com.cn/problem/CF1839E'
    },
    {
        id: 'fragmented-nim',
        name: '碎片化 Nim',
        icon: '🧩',
        description: '你选堆，对手指定你从哪堆取！当前仅实现普通 Nim 规则。',
        difficulty: 'hard',
        defaultPiles: [3, 5, 7],
        maxTake: null,
        rule: 'fragmented-nim',
        timeLimit: 60,
        boardType: 'multi-pile',
        ai: { style: 'tricky' },
        customizable: true,
        configLabel: '堆数',
        configPlaceholder: '堆数',
        link: 'https://www.luogu.com.cn/problem/CF2181F'
    },
    {
        id: 'letter-picking',
        name: '字符串取牌',
        icon: '🔤',
        description: '从字符串两端取字符拼成自己的序列，比字典序大小。',
        difficulty: 'hard',
        defaultPiles: [],
        defaultWord: 'ABBAABBA',
        maxTake: null,
        rule: 'letter-picking',
        timeLimit: 90,
        boardType: 'text',
        ai: { style: 'random' },
        customizable: true,
        configLabel: '字符串（偶数长度）',
        configPlaceholder: '如 ABBA',
        link: 'https://www.luogu.com.cn/problem/CF1728D'
    }
];